### ISSUE TITLE
LV2 not working?

### ISSUE THREAD

**Issue by rominator1983** [GuitarML/SmartGuitarPedal#10]
I tried to install/run the deb or build/run the plugin myself but get stuck at runtime with a loading error: ```lilv_plugin_instantiate(): error: No plugin <file:///plugins/SmartPedal> in <file:///usr/lib/lv2/SmartPedal.lv2/libSmartPedal.so>```
I am trying to run the plugin using jalv.select.

I checked and I think that the manifest.ttl is broken. When looking at other plugins there are URIs defining the plugins whereas here there are something like absolute paths?!?
I am talking about the line ```</plugins/SmartPedal>```
```
@prefix lv2:   <http://lv2plug.in/ns/lv2core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix pset:  <http://lv2plug.in/ns/ext/presets#> .
@prefix state: <http://lv2plug.in/ns/ext/state#> .
@prefix ui:    <http://lv2plug.in/ns/extensions/ui#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .

</plugins/SmartPedal>
	a lv2:Plugin ;
	lv2:binary <libSmartPedal.so> ;
	rdfs:seeAlso <dsp.ttl> .

</plugins/SmartPedal:UI>
	a ui:X11UI ;
	lv2:binary <libSmartPedal.so> ;
	rdfs:seeAlso <ui.ttl> .

</plugins/SmartPedal:preset1>
	a pset:Preset ;
	lv2:appliesTo </plugins/SmartPedal> ;
	rdfs:label "" ;
	state:state [ </plugins/SmartPedal:Program> "0"^^xsd:int ; ] .
```

Unfortunately I do not know where this should be fixed and what URIs you want to use for your plugins.
Could you have a look into that?

**Comment by rominator1983** [comment]
I forgot. I was building from master or using the latest release. Same error for both.

**Comment by rominator1983** [comment]
Plenty of samples of there. Here is one I did a while ago:
https://github.com/rominator1983/justOneOctaveUp.lv2/releases/download/1.0/manifest.ttl

**Comment by rominator1983** [comment]
That might help too:
https://lv2plug.in/pages/bundle-definition.html

**Comment by rominator1983** [comment]
I played around with the .ttl files and replaced `/plugins/SmartPedal` with `https://github.com/GuitarML/SmartPedal` (the URL that is also used in CMakeLists.txt) after that I now do get the error `lilv_plugin_instantiate(): error: No plugin <https://github.com/GuitarML/SmartPedal> in <file:///usr/lib/lv2/SmartPedal.lv2/libSmartPedal.so>`

This does not make sense to me as this seems to work for your NeuralPI plugin. The call (or whatever it is) to juce_add_plugin in CMakeLists.txt looks pretty similar for the two projects.

**Comment by GuitarML** [comment]
One difference between those is for EpochAmp I used the official JUCE 7 release, which is supposed to fully support LV2, and for NeuralPi I used https://github.com/lv2-porting-project/JUCE.git

I might try building with the old lv2 porting code and seeing if there are any differences in the .ttl

**Comment by rominator1983** [comment]
TTL of Neuralpi looks good and works btw.

**Comment by GuitarML** [comment]
@rominator1983 I figured out the the URL I was using was incorrect, should have been "SmartGuitarPedal" and not just "SmartPedal", so if there's some kind of verification step that the url works that might be the issue.  I used the correct URL in my latest release, version 1.5.

**Comment by rominator1983** [comment]
I found it in the warnings when looking at the output of `cmake -Bbuild`:
```
CMake Warning at modules/JUCE/extras/Build/CMake/JUCEUtils.cmake:1015 (message):
  LV2URI should be well-formed with an 'http' prefix.  Check the LV2URI
  argument to juce_add_plugin.
Call Stack (most recent call first):
  modules/JUCE/extras/Build/CMake/JUCEUtils.cmake:1123 (_juce_set_plugin_target_properties)
  modules/JUCE/extras/Build/CMake/JUCEUtils.cmake:1261 (_juce_link_plugin_wrapper)
  modules/JUCE/extras/Build/CMake/JUCEUtils.cmake:1806 (_juce_configure_plugin_targets)
  CMakeLists.txt:26 (juce_add_plugin)
```
Of course the message did not print the actual value. Turns out it was set to some default value and the URL set in `CMakeLists.txt` was not used at all. The parameter _name_ to the call to` juce_add_plugin` should have been `LV2URI` when it was `LV2_URI`.

It is now spinning up on my machine in jalv.select. Net thing on the list is getting the thing to work in MOD!
Here is a PR for you: https://github.com/GuitarML/SmartGuitarPedal/pull/15

**Comment by GuitarML** [comment]
@rominator1983 Thanks for figuring that out! Closing issue, fixed in: https://github.com/GuitarML/SmartGuitarPedal/pull/15
