### ISSUE TITLE
Xcode macOS settings

### ISSUE THREAD

**Issue by nikolayrantsev** [GuitarML/SmartGuitarPedal#2]
Hi, 

It might be useful info for mac users - by default the Projucer microphone access setting value set to "Disabled", so you can't hear input signal from your audio interface. Allow microphone usage here in the Projucer project before building in Xcode:
Exporters-> Xcode(macOS)-> Microphone Access: **Enabled**

I assume there are specific settings for file access. The app on mac doesn't show any .json models in the dropdown UI control above the knobs - even if they are the same folder as the app itself (works fine on Windows). Can somebody help with that?

Thank you

**Comment by keyth72** [comment]
Good catch, I’ve noticed that the drop down menu also does not work in Ubuntu Linux. Might be something specific to the Windows file system with how I’m handling that.

**Comment by GuitarML** [comment]
Fixed in version 1.4, closing issue
