### ISSUE TITLE
Drop down menu doesn’t pick up .json file when using Mac or Linux

### ISSUE THREAD

**Issue by GuitarML** [GuitarML/SmartGuitarPedal#3]
Rewrite json file loading so that it works across all platforms.

**Comment by keyth72** [comment]
Added a load model button as a work around for the time being. It seems at least for Ubuntu Linux, if you put the models in the same directory as a DAW shortcut (like a desktop shortcut) it will pick up the models in the drop down.

**Comment by usdivad** [comment]
Do you think using e.g. `File::getSpecialLocation(File::userApplicationDataDirectory)` would help sidestep any permissions issues with the directory containing the executable?

Based on the JUCE source code, that corresponds to:
Mac: `~/Library/`
Linux: `~/.config`
Windows: `C:\Users\[username]\AppData\Roaming`

And then you could append e.g. `GuitarML/SmartGuitarPedal` or something to the path name, and use that as the `currentDirectory` (or even call `SmartPedalAudioProcessor::addDirectory()` on both `File::userApplicationDataDirectory` and `File::getCurrentWorkingDirectory()`)

I think `File::commonDocumentsDirectory` could work too, as it should also have read/write permissions by default.

Using `File::userApplicationDataDirectory` seems to work well on with initial tests on my Mac -- would be happy to whip something up so folks can try it on Windows and Linux as well!

**Comment by GuitarML** [comment]
@usdivad that sounds great, I wasn't aware of those JUCE functions, but yes using the standard locations for read/write is a good idea.
